### ISSUE TITLE
#2 - Adição da equipe no github pages

### ISSUE THREAD

**Issue by Neitan2001** [Interacao-Humano-Computador/2022.1-Grupo-08#2]
## Descrição
Adição dos membros da equipe no github pages
## Tarefas

- [x] Adicionar equipe
- [x] Listar nome e colocar foto de cada membro do time

## Fotos adicionadas nos comentários
- [x] Clara Marcelino
- [x] Luiza Esteves
- [x] Natan Tavares
- [x] Matheus Perillo
- [x] Rafael Xavier
- [x] Daniel

## Critério de aceitação

- [x] Criação revisada pelo revisor
- [x] Ortografia revisada

**Comment by MatheusPerillo** [comment]
![fotoperillao](https://user-images.githubusercontent.com/87678152/176207310-9c6cf4eb-414c-4b3b-854f-86696d43a6dc.jpg)

**Comment by luiza-esteves** [comment]
![i](https://user-images.githubusercontent.com/69515514/176426947-3256ab9c-4751-4137-a0db-ee03322ba2a7.jpeg)

**Comment by DanielCoimbra** [comment]
![profile_pic](https://user-images.githubusercontent.com/49206670/176682591-783d861f-5728-4df5-b7d0-35f881bb764d.png)

**Comment by clara-ribeiro** [comment]
![photo1656614355](https://user-images.githubusercontent.com/64803940/176753508-a651937a-e57f-4c76-855b-a4c7ef16c119.jpeg)
